version: "4.42"
services:
  chatUsersDb:
    image: postgres
    container_name: postgres
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chatUsersDb